// VBConversions Note: VB project level imports
using System.Data;
using System.Diagnostics;
using System.Xml.Linq;
using System.Drawing;
using System.Collections.Generic;
using Microsoft.VisualBasic;
using System.Collections;
using System;
using System.Windows.Forms;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;
using System.IO;
// End of VB project level imports


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace CableStayedBridge
{
	namespace My
	{
		
		[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute(), 
		global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"), 
		global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
		{
			
			private static Settings defaultInstance = (My.Settings) (global::System.Configuration.ApplicationSettingsBase.Synchronized(new My.Settings()));
			
#region My.Settings Auto-Save Functionality
#if _MyType
			private static bool addedHandler;
			
			private static object addedHandlerLockObject = new object();
			
			[global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]private static void AutoSaveSettings(global::System.Object sender, global::System.EventArgs e)
			{
				if ((new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase()).SaveMySettingsOnExit)
				{
					My.Settings.Default.Save();
				}
			}
#endif
#endregion
			
public static Settings Default
			{
				get
				{
					
#if _MyType
					if (!addedHandler)
					{
						lock(addedHandlerLockObject)
						{
							if (!addedHandler)
							{
								(new Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase).Shutdown += AutoSaveSettings;
								addedHandler = true;
							}
						}
					}
#endif
					return defaultInstance;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
DebuggerNonUserCode(), 
global::System.Configuration.DefaultSettingValueAttribute("False")]public string Path_MainForm
			{
				get
				{
					return System.Convert.ToString(this["Path_MainForm"]);
				}
				set
				{
					this["Path_MainForm"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
DebuggerNonUserCode(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string Path_Template
			{
				get
				{
					return System.Convert.ToString(this["Path_Template"]);
				}
				set
				{
					this["Path_Template"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
DebuggerNonUserCode(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string Path_Output
			{
				get
				{
					return System.Convert.ToString(this["Path_Output"]);
				}
				set
				{
					this["Path_Output"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
DebuggerNonUserCode(), 
global::System.Configuration.DefaultSettingValueAttribute("")]public string Path_DataBase
			{
				get
				{
					return System.Convert.ToString(this["Path_DataBase"]);
				}
				set
				{
					this["Path_DataBase"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
DebuggerNonUserCode(), 
global::System.Configuration.DefaultSettingValueAttribute("B03")]public string ProjectRegion
			{
				get
				{
					return System.Convert.ToString(this["ProjectRegion"]);
				}
				set
				{
					this["ProjectRegion"] = value;
				}
			}
			
[global::System.Configuration.UserScopedSettingAttribute(), 
DebuggerNonUserCode(), 
global::System.Configuration.DefaultSettingValueAttribute("后世博")]public string ProjectName
			{
				get
				{
					return System.Convert.ToString(this["ProjectName"]);
				}
				set
				{
					this["ProjectName"] = value;
				}
			}
		}
	}
	
	namespace My
	{
		
		[HideModuleName(), 
		DebuggerNonUserCode(), 
		global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]internal sealed class MySettingsProperty
		{
			
[global::System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")]internal static global::CableStayedBridge.My.Settings Settings
			{
				get
				{
					return global::CableStayedBridge.My.Settings.Default;
				}
			}
		}
	}
	
}
